"""
YOLO Building Detection Model Training Script

This script trains a YOLOv8 model on the GeoBizkaia building detection dataset.
The dataset is generated by yolo_data_builder.py and stored in YOLO format.

Usage:
    python train_yolo_model.py --model yolov8n --epochs 100 --imgsz 4096
    python train_yolo_model.py --model m --epochs 50 --batch 20 --device 0
    python train_yolo_model.py --resume path/to/runs/detect/train/weights/last.pt

Features:
    - Multiple model sizes (nano, small, medium, large, xlarge)
    - Configurable training parameters
    - Resume training from checkpoint
    - Automatic best model tracking
    - Training metrics and validation results
    - Inference on test set after training
"""

import argparse
import logging
from pathlib import Path
from typing import Optional
import sys
import json
from datetime import datetime
from ultralytics import YOLO
from ultralytics.utils import LOGGER

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.FileHandler("training.log"), logging.StreamHandler()],
)
logger = logging.getLogger(__name__)


class YOLOTrainer:
    """Manages YOLOv8 training pipeline for building detection."""

    def __init__(
        self,
        data_yaml: str = "../../dataset/yolo_buildings/data.yaml",
        model_size: str = "n",
        epochs: int = 100,
        imgsz: int = 4096,  # image 4096x4096 pixels
        batch_size: int = 4,
        device: int = 0,
        patience: int = 20,
        save_dir: str = "../../model/runs",
    ):
        """
        Initialize the YOLO trainer.

        Args:
            data_yaml: Path to data.yaml configuration
            model_size: Model size ('n', 's', 'm', 'l', 'x')
            epochs: Number of training epochs
            imgsz: Input image size
            batch_size: Batch size for training
            device: GPU device ID (0, 1, 2, ...) or 'cpu'
            patience: Early stopping patience
            save_dir: Directory to save training results
        """
        self.data_yaml = Path(data_yaml).resolve()
        self.model_size = model_size
        self.epochs = epochs
        self.imgsz = imgsz
        self.batch_size = batch_size
        self.device = device
        self.patience = patience
        self.save_dir = Path(save_dir).resolve()

        # Validate data.yaml exists
        if not self.data_yaml.exists():
            raise FileNotFoundError(f"data.yaml not found at {self.data_yaml}")

        logger.info(f"Initialized YOLOTrainer with model size: {model_size}")
        logger.info(f"Data config: {self.data_yaml}")
        logger.info(f"Save directory: {self.save_dir}")

    def _print_config(self):
        """Print training configuration."""
        config = {
            "Model Size": f"yolov8{self.model_size}",
            "Data Config": str(self.data_yaml),
            "Epochs": self.epochs,
            "Batch Size": self.batch_size,
            "Image Size": self.imgsz,
            "Device": self.device,
            "Early Stopping Patience": self.patience,
            "Save Directory": str(self.save_dir),
        }

        logger.info("=" * 60)
        logger.info("YOLO TRAINING CONFIGURATION")
        logger.info("=" * 60)
        for key, value in config.items():
            logger.info(f"  {key}: {value}")
        logger.info("=" * 60)

    def _prepare_images(self):
        """
        Prepare images for training by converting 4-channel to 3-channel if needed.

        This handles TIFF files with 4 channels (e.g., RGBA or geospatial bands)
        by dropping the alpha channel or extra bands, keeping only RGB.
        """
        import warnings

        warnings.filterwarnings("ignore")  # Suppress geospatial TIFF warnings

        try:
            import rasterio
            import numpy as np
        except ImportError:
            try:
                from PIL import Image
                import numpy as np

                logger.info("PIL available, will use for image conversion")
            except ImportError:
                logger.warning(
                    "Neither rasterio nor PIL available. Skipping image channel conversion."
                )
                logger.warning("Images may fail to load if they have 4 channels.")
                return

        # Get all image splits
        images_dir = Path(self.data_yaml).parent / "images"

        for split in ["train", "val", "test"]:
            split_dir = images_dir / split
            if not split_dir.exists():
                continue

            logger.info(f"Checking {split} images for channel conversion...")
            tiff_files = list(split_dir.glob("*.tif")) + list(split_dir.glob("*.tiff"))

            if not tiff_files:
                logger.info(f"No TIFF files found in {split}")
                continue

            for img_path in tiff_files:
                try:
                    # Try using rasterio first (for geospatial TIFF)
                    with rasterio.open(img_path) as src:
                        if src.count > 3:
                            logger.info(
                                f"Converting {img_path.name} from {src.count} channels to 3-channel RGB..."
                            )

                            # Read first 3 bands
                            data = src.read([1, 2, 3])

                            # Normalize to 0-255 range if needed
                            if data.dtype != np.uint8:
                                # Get min/max for normalization
                                data_min = data.min()
                                data_max = data.max()
                                if data_max > data_min:
                                    data = (
                                        (data - data_min) / (data_max - data_min) * 255
                                    ).astype(np.uint8)
                                else:
                                    data = data.astype(np.uint8)

                            # Save as PNG (preserves quality better than JPEG for geospatial)
                            from PIL import Image as PILImage

                            # Convert from (3, H, W) to (H, W, 3)
                            rgb_array = np.transpose(data, (1, 2, 0))
                            rgb_img = PILImage.fromarray(rgb_array, mode="RGB")

                            new_path = img_path.with_suffix(".png")
                            rgb_img.save(new_path)
                            logger.info(f"Saved converted image as {new_path.name}")

                            # Remove original TIFF with retry logic (handles file locking)
                            import time

                            max_retries = 3
                            for attempt in range(max_retries):
                                try:
                                    img_path.unlink()
                                    logger.info(f"Removed original {img_path.name}")
                                    break
                                except PermissionError:
                                    if attempt < max_retries - 1:
                                        logger.warning(
                                            f"File locked, retrying in 0.5s... ({attempt + 1}/{max_retries})"
                                        )
                                        time.sleep(0.5)
                                    else:
                                        logger.warning(
                                            f"Could not remove {img_path.name} (file is locked). Will be removed later."
                                        )
                        else:
                            logger.info(
                                f"{img_path.name} already has {src.count} channels, no conversion needed"
                            )

                except Exception as e:
                    logger.warning(f"Failed to convert {img_path.name}: {str(e)}")
                    logger.warning("Continuing with original image format...")

    def train(self, resume: Optional[str] = None) -> dict:
        """
        Train the YOLO model.

        Args:
            resume: Path to checkpoint to resume training from

        Returns:
            Dictionary with training results
        """
        self._print_config()

        # Prepare images (convert 4-channel to 3-channel if needed)
        self._prepare_images()

        try:
            # Load model
            model_name = f"yolov8{self.model_size}.pt"
            logger.info(f"Loading model: {model_name}")
            model = YOLO(model_name)

            # Prepare training arguments
            train_args = {
                "data": str(self.data_yaml),
                "epochs": self.epochs,
                "imgsz": self.imgsz,
                "batch": self.batch_size,
                "device": self.device,
                "patience": self.patience,
                "save": True,
                "save_period": 5,  # Save every 5 epochs
                "exist_ok": False,
                "verbose": True,
                "project": str(self.save_dir),
                "name": f"train_yolov8{self.model_size}_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            }

            # Add resume if provided
            if resume:
                logger.info(f"Resuming training from: {resume}")
                train_args["resume"] = resume

            # Train the model
            logger.info("Starting training...")
            results = model.train(**train_args)

            logger.info("Training completed successfully!")
            logger.info(f"Best model saved to: {results.save_dir}/weights/best.pt")
            logger.info(f"Last model saved to: {results.save_dir}/weights/last.pt")

            return {
                "status": "success",
                "model": model_name,
                "epochs": self.epochs,
                "save_dir": str(results.save_dir),
                "best_weights": str(Path(results.save_dir) / "weights" / "best.pt"),
                "last_weights": str(Path(results.save_dir) / "weights" / "last.pt"),
            }

        except Exception as e:
            logger.error(f"Training failed: {str(e)}", exc_info=True)
            raise

    def validate(self, weights: str) -> dict:
        """
        Validate the trained model on validation set.

        Args:
            weights: Path to model weights

        Returns:
            Validation metrics
        """
        logger.info(f"Validating model: {weights}")

        try:
            model = YOLO(weights)
            metrics = model.val(data=str(self.data_yaml))

            logger.info("Validation completed successfully!")
            return {
                "status": "success",
                "metrics": metrics,
            }

        except Exception as e:
            logger.error(f"Validation failed: {str(e)}", exc_info=True)
            raise

    def test(self, weights: str) -> dict:
        """
        Test the trained model on test set.

        Args:
            weights: Path to model weights

        Returns:
            Test results
        """
        logger.info(f"Testing model: {weights}")

        try:
            model = YOLO(weights)
            results = model.val(
                data=str(self.data_yaml),
                split="test",
            )

            logger.info("Testing completed successfully!")
            return {
                "status": "success",
                "results": results,
            }

        except Exception as e:
            logger.error(f"Testing failed: {str(e)}", exc_info=True)
            raise


def main():
    """Main entry point for training script."""

    parser = argparse.ArgumentParser(
        description="Train YOLOv8 model for building detection",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic training with default settings
  python train_yolo_model.py

  # Train with specific model size and epochs
  python train_yolo_model.py --model m --epochs 50

  # Train with large model on GPU 0
  python train_yolo_model.py --model l --epochs 100 --device 0

  # Resume training from checkpoint
  python train_yolo_model.py --resume path/to/runs/detect/train/weights/last.pt

  # Train with custom batch size and image size
  python train_yolo_model.py --batch 8 --imgsz 2048
        """,
    )

    parser.add_argument(
        "--model",
        type=str,
        default="n",
        choices=["n", "s", "m", "l", "x"],
        help="Model size: nano (n), small (s), medium (m), large (l), xlarge (x). Default: nano",
    )

    parser.add_argument(
        "--epochs",
        type=int,
        default=100,
        help="Number of training epochs. Default: 100",
    )

    parser.add_argument(
        "--imgsz",
        type=int,
        default=4096,
        help="Input image size. Default: 4096 (matches dataset size)",
    )

    parser.add_argument(
        "--batch",
        type=int,
        default=4,
        help="Batch size. Default: 4 (adjust based on GPU memory)",
    )

    def parse_device(device_str):
        """Parse device argument to handle both int and string values."""
        if str(device_str).lower() == "cpu":
            return -1
        try:
            return int(device_str)
        except ValueError:
            raise argparse.ArgumentTypeError(
                f"device must be an integer, -1 for CPU, or 'cpu'. Got: {device_str}"
            )

    parser.add_argument(
        "--device",
        type=parse_device,
        default=0,
        help="GPU device ID (0, 1, 2, ...), -1 for CPU, or 'cpu'. Default: 0",
    )

    parser.add_argument(
        "--patience",
        type=int,
        default=20,
        help="Early stopping patience (epochs without improvement). Default: 20",
    )

    parser.add_argument(
        "--data",
        type=str,
        default="../../dataset/yolo_buildings/data.yaml",
        help="Path to data.yaml configuration. Default: ../../dataset/yolo_buildings/data.yaml",
    )

    parser.add_argument(
        "--save-dir",
        type=str,
        default="../../model/runs",
        help="Directory to save training results. Default: ../../model/runs",
    )

    parser.add_argument(
        "--resume",
        type=str,
        default=None,
        help="Path to checkpoint to resume training from",
    )

    parser.add_argument(
        "--validate-only", action="store_true", help="Only validate without training"
    )

    parser.add_argument(
        "--test-only",
        type=str,
        default=None,
        metavar="WEIGHTS",
        help="Only test model with given weights path",
    )

    args = parser.parse_args()

    try:
        # Create trainer
        trainer = YOLOTrainer(
            data_yaml=args.data,
            model_size=args.model,
            epochs=args.epochs,
            imgsz=args.imgsz,
            batch_size=args.batch,
            device=args.device,
            patience=args.patience,
            save_dir=args.save_dir,
        )

        # Execute requested operation
        if args.test_only:
            # Test only mode
            logger.info("Running test-only mode...")
            trainer.test(args.test_only)

        elif args.validate_only:
            # Validate only mode
            logger.info("Running validation-only mode...")
            trainer.validate(args.resume or f"yolov8{args.model}.pt")

        else:
            # Full training pipeline
            logger.info("Running full training pipeline...")

            # Train
            train_result = trainer.train(resume=args.resume)
            best_weights = train_result["best_weights"]

            # Validate
            logger.info("\nValidating best model...")
            trainer.validate(best_weights)

            # Test
            logger.info("\nTesting on test set...")
            trainer.test(best_weights)

            # Summary
            logger.info("\n" + "=" * 60)
            logger.info("TRAINING COMPLETE")
            logger.info("=" * 60)
            logger.info(f"Best model: {best_weights}")
            logger.info(f"Results saved to: {train_result['save_dir']}")
            logger.info("=" * 60)

    except Exception as e:
        logger.error(f"Fatal error: {str(e)}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
